

- dataframe créé (0.5 %)- pseudocode définie (1%)-
indexation utilisée (2 %)- combinaison des données (2 %)-
Numpy code implémenté (2%)- « groupby » est utilisé (2.5 %)-
remise en fichier .ipynb sur GitHub, le plus tard à 23h59 du 
jour prévu.

In [1]:
import pandas as pd
import numpy as np
import matplotlib

In [2]:
#création du dataframe 
df = pd.read_csv('JulieDandrimont_données_psy3019-H23_20230204_Maltreatment_Types_of_Victims.csv')
df

,State,Medical Neglect Only,Neglect Only,Other Only,Physical Abuse Only,Psychological Maltreatment Only,Sexual Abuse Only,Sex Trafficking Only,Unknown Only,Multiple Maltreatment Types,...,Medical Neglect Only Percent,Neglect Only Percent,Other Only Percent,Physical Abuse Only Percent,Psychological Maltreatment Only Percent,Sexual Abuse Only Percent,Sex Trafficking Only Percent,Unknown Only Percent,Multiple Maltreatment Types Percent,Total Victims Percent
0,Alabama,49.0,3380,NaN,5114,16.0,1828.0,3.0,NaN,1287,...,0.4,28.9,NaN,43.8,0.1,15.7,0.0,NaN,11.0,100.0
1,Alaska,37.0,1445,NaN,111,327.0,183.0,1.0,NaN,955,...,1.2,47.2,NaN,3.6,10.7,6.0,0.0,NaN,31.2,100.0
2,Arizona,NaN,11332,NaN,682,1.0,389.0,NaN,NaN,443,...,NaN,88.2,NaN,5.3,0.0,3.0,NaN,NaN,3.4,100.0
3,Arkansas,1279.0,3421,1.0,1286,25.0,1415.0,NaN,NaN,995,...,15.2,40.6,0.0,15.3,0.3,16.8,NaN,NaN,11.8,100.0
4,California,NaN,50799,117.0,2161,2115.0,2264.0,NaN,NaN,6659,...,NaN,79.2,0.2,3.4,3.3,3.5,NaN,NaN,10.4,100.0
5,Colorado,80.0,9517,NaN,854,126.0,990.0,NaN,9.0,670,...,0.7,77.7,NaN,7.0,1.0,8.1,NaN,0.1,5.5,100.0
6,Connecticut,87.0,4709,NaN,172,599.0,181.0,NaN,NaN,2294,...,1.1,58.6,NaN,2.1,7.4,2.3,NaN,NaN,28.5,100.0
7,Delaware,NaN,313,120.0,161,404.0,121.0,NaN,NaN,129,...,NaN,25.1,9.6,12.9,32.4,9.7,NaN,NaN,10.3,100.0
8,District of Columbia,NaN,1492,NaN,175,NaN,45.0,14.0,NaN,131,...,NaN,80.3,NaN,9.4,NaN,2.4,0.8,NaN,7.1,100.0
9,Florida,616.0,12893,8201.0,1742,156.0,2354.0,NaN,NaN,6953,...,1.9,39.2,24.9,5.3,0.5,7.2,NaN,NaN,21.1,100.0
10,Georgia,148.0,5992,NaN,840,1447.0,693.0,27.0,NaN,955,...,1.5,59.3,NaN,8.3,14.3,6.9,0.3,NaN,9.5,100.0
11,Hawaii,NaN,47,918.0,31,2.0,23.0,13.0,NaN,308,...,NaN,3.5,68.4,2.3,0.1,1.7,1.0,NaN,23.0,100.0
12,Idaho,7.0,1349,3.0,306,NaN,100.0,NaN,NaN,104,...,0.4,72.2,0.2,16.4,NaN,5.4,NaN,NaN,5.6,100.0
13,Illinois,441.0,22234,22.0,3856,29.0,3798.0,NaN,NaN,2951,...,1.3,66.7,0.1,11.6,0.1,11.4,NaN,NaN,8.9,100.0
14,Indiana,NaN,19006,NaN,856,NaN,2060.0,4.0,NaN,1103,...,NaN,82.5,NaN,3.7,NaN,8.9,0.0,NaN,4.8,100.0
15,Iowa,44.0,6105,1754.0,845,43.0,566.0,NaN,NaN,2291,...,0.4,52.4,15.1,7.3,0.4,4.9,NaN,NaN,19.7,100.0
16,Kansas,58.0,1162,1.0,600,343.0,519.0,7.0,NaN,255,...,2.0,39.5,0.0,20.4,11.6,17.6,0.2,NaN,8.7,100.0
17,Kentucky,127.0,17670,NaN,381,14.0,376.0,NaN,NaN,1562,...,0.6,87.8,NaN,1.9,0.1,1.9,NaN,NaN,7.8,100.0
18,Louisiana,NaN,6954,NaN,690,11.0,339.0,1.0,NaN,446,...,NaN,82.4,NaN,8.2,0.1,4.0,0.0,NaN,5.3,100.0
19,Maine,NaN,1839,NaN,460,679.0,217.0,NaN,NaN,1218,...,NaN,41.7,NaN,10.4,15.4,4.9,NaN,NaN,27.6,100.0
20,Maryland,NaN,4221,NaN,1182,7.0,1748.0,NaN,NaN,503,...,NaN,55.1,NaN,15.4,0.1,22.8,NaN,NaN,6.6,100.0
21,Massachusetts,NaN,22067,NaN,838,NaN,443.0,187.0,NaN,1494,...,NaN,88.2,NaN,3.3,NaN,1.8,0.7,NaN,6.0,100.0
22,Michigan,349.0,25823,NaN,2950,103.0,676.0,14.0,NaN,3128,...,1.1,78.1,NaN,8.9,0.3,2.0,0.0,NaN,9.5,100.0
23,Minnesota,NaN,4127,NaN,691,50.0,1292.0,20.0,NaN,600,...,NaN,60.9,NaN,10.2,0.7,19.1,0.3,NaN,8.8,100.0
24,Mississippi,191.0,5202,1.0,777,480.0,888.0,3.0,NaN,1835,...,2.0,55.5,0.0,8.3,5.1,9.5,0.0,NaN,19.6,100.0
25,Missouri,23.0,1549,5.0,665,90.0,1199.0,6.0,NaN,1225,...,0.5,32.5,0.1,14.0,1.9,25.2,0.1,NaN,25.7,100.0
26,Montana,3.0,3444,NaN,44,3.0,39.0,NaN,NaN,203,...,0.1,92.2,NaN,1.2,0.1,1.0,NaN,NaN,5.4,100.0
27,Nebraska,NaN,2190,NaN,229,4.0,228.0,NaN,NaN,171,...,NaN,77.6,NaN,8.1,0.1,8.1,NaN,NaN,6.1,100.0
28,Nevada,33.0,3680,NaN,540,3.0,215.0,NaN,NaN,528,...,0.7,73.6,NaN,10.8,0.1,4.3,NaN,NaN,10.6,100.0
29,New Hampshire,18.0,948,NaN,47,9.0,84.0,NaN,NaN,111,...,1.5,77.9,NaN,3.9,0.7,6.9,NaN,NaN,9.1,100.0
30,New Jersey,65.0,3545,1.0,485,32.0,703.0,1.0,NaN,300,...,1.3,69.1,0.0,9.5,0.6,13.7,0.0,NaN,5.8,100.0
31,New Mexico,67.0,4747,NaN,420,721.0,111.0,NaN,NaN,1959,...,0.8,59.2,NaN,5.2,9.0,1.4,NaN,NaN,24.4,100.0
32,New York,453.0,38395,1564.0,547,40.0,345.0,NaN,NaN,25925,...,0.7,57.1,2.3,0.8,0.1,0.5,NaN,NaN,38.5,100.0
33,North Carolina,49.0,2455,108.0,1575,105.0,1195.0,NaN,44.0,70,...,0.9,43.8,1.9,28.1,1.9,21.3,NaN,0.8,1.2,100.0
34,North Dakota,6.0,1106,NaN,62,256.0,45.0,NaN,NaN,322,...,0.3,61.5,NaN,3.5,14.2,2.5,NaN,NaN,17.9,100.0
35,Ohio,252.0,8333,NaN,8123,776.0,3905.0,NaN,NaN,4081,...,1.0,32.7,NaN,31.9,3.0,15.3,NaN,NaN,16.0,100.0
36,Oklahoma,88.0,7824,NaN,849,2310.0,396.0,2.0,NaN,3679,...,0.6,51.7,NaN,5.6,15.2,2.6,0.0,NaN,24.3,100.0
37,Oregon,64.0,4426,4595.0,861,72.0,757.0,18.0,NaN,2750,...,0.5,32.7,33.9,6.4,0.5,5.6,0.1,NaN,20.3,100.0
38,Pennsylvania,160.0,373,21.0,1961,48.0,2007.0,17.0,NaN,230,...,3.3,7.7,0.4,40.7,1.0,41.7,0.4,NaN,4.8,100.0
39,Puerto Rico,76.0,1576,10.0,245,815.0,41.0,NaN,NaN,1975,...,1.6,33.3,0.2,5.2,17.2,0.9,NaN,NaN,41.7,100.0
40,Rhode Island,25.0,1436,51.0,288,802.0,110.0,NaN,NaN,471,...,0.8,45.1,1.6,9.0,25.2,3.5,NaN,NaN,14.8,100.0
41,South Carolina,153.0,7073,13.0,7403,29.0,593.0,NaN,3.0,3450,...,0.8,37.8,0.1,39.6,0.2,3.2,NaN,NaN,18.4,100.0
42,South Dakota,NaN,1319,NaN,76,2.0,39.0,NaN,NaN,101,...,NaN,85.8,NaN,4.9,0.1,2.5,NaN,NaN,6.6,100.0
43,Tennessee,42.0,1199,NaN,4671,172.0,2159.0,88.0,NaN,1528,...,0.4,12.2,NaN,47.4,1.7,21.9,0.9,NaN,15.5,100.0
44,Texas,417.0,48404,3.0,4086,116.0,5753.0,5.0,NaN,5309,...,0.7,75.5,0.0,6.4,0.2,9.0,0.0,NaN,8.3,100.0
45,Utah,25.0,1953,105.0,2944,2051.0,1506.0,1.0,NaN,1994,...,0.2,18.5,1.0,27.8,19.4,14.2,0.0,NaN,18.8,100.0
46,Vermont,11.0,13,NaN,463,1.0,327.0,NaN,NaN,36,...,1.3,1.5,NaN,54.4,0.1,38.4,NaN,NaN,4.2,100.0
47,Virginia,69.0,3444,NaN,1303,39.0,698.0,NaN,NaN,606,...,1.1,55.9,NaN,21.2,0.6,11.3,NaN,NaN,9.8,100.0
48,Washington,NaN,2831,NaN,569,NaN,337.0,7.0,NaN,478,...,NaN,67.1,NaN,13.5,NaN,8.0,0.2,NaN,11.3,100.0
49,West Virginia,NaN,1173,NaN,902,NaN,NaN,NaN,NaN,4652,...,NaN,17.4,NaN,13.4,NaN,NaN,NaN,NaN,69.2,100.0
50,Wisconsin,NaN,2802,NaN,546,10.0,845.0,NaN,NaN,373,...,NaN,61.2,NaN,11.9,0.2,18.5,NaN,NaN,8.2,100.0
51,Wyoming,2.0,655,NaN,13,189.0,60.0,NaN,NaN,177,...,0.2,59.8,NaN,1.2,17.2,5.5,NaN,NaN,16.1,100.0
52,National,5614.0,399992,17614.0,67678,15672.0,47205.0,439.0,56.0,101973,...,0.9,61.0,2.7,10.3,2.4,7.2,0.1,0.0,15.5,100.0
53,Reporting States,36.0,52,21.0,52,46.0,51.0,21.0,3.0,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.tail()

,State,Medical Neglect Only,Neglect Only,Other Only,Physical Abuse Only,Psychological Maltreatment Only,Sexual Abuse Only,Sex Trafficking Only,Unknown Only,Multiple Maltreatment Types,...,Medical Neglect Only Percent,Neglect Only Percent,Other Only Percent,Physical Abuse Only Percent,Psychological Maltreatment Only Percent,Sexual Abuse Only Percent,Sex Trafficking Only Percent,Unknown Only Percent,Multiple Maltreatment Types Percent,Total Victims Percent
49,West Virginia,NaN,1173,NaN,902,NaN,NaN,NaN,NaN,4652,...,NaN,17.4,NaN,13.4,NaN,NaN,NaN,NaN,69.2,100.0
50,Wisconsin,NaN,2802,NaN,546,10.0,845.0,NaN,NaN,373,...,NaN,61.2,NaN,11.9,0.2,18.5,NaN,NaN,8.2,100.0
51,Wyoming,2.0,655,NaN,13,189.0,60.0,NaN,NaN,177,...,0.2,59.8,NaN,1.2,17.2,5.5,NaN,NaN,16.1,100.0
52,National,5614.0,399992,17614.0,67678,15672.0,47205.0,439.0,56.0,101973,...,0.9,61.0,2.7,10.3,2.4,7.2,0.1,0.0,15.5,100.0
53,Reporting States,36.0,52,21.0,52,46.0,51.0,21.0,3.0,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
colonnes = df.columns.tolist()
print(colonnes)

print(colonnes.index('Total Victims'))
print(colonnes[10])

['State', 'Medical Neglect Only', 'Neglect Only', 'Other Only', 'Physical Abuse Only', 'Psychological Maltreatment Only', 'Sexual Abuse Only', 'Sex Trafficking Only', 'Unknown Only', 'Multiple Maltreatment Types', 'Total Victims', 'Medical Neglect Only Percent', 'Neglect Only Percent', 'Other Only Percent', 'Physical Abuse Only Percent', 'Psychological Maltreatment Only Percent', 'Sexual Abuse Only Percent', 'Sex Trafficking Only Percent', 'Unknown Only Percent', 'Multiple Maltreatment Types Percent', 'Total Victims Percent']
10
Total Victims

opérateurs de comparaison présents (1%)- 

opérateurs d’agrégation présents (1%) = sum and mean etrc

valeurs manquantes cherchées (2%)- 

condition « if » utilisée (2 %)- 

boucle « for » utilisé (2 %)- 

boucle « while » utilisé (2 %)- 

histogramme présent (2.5 %)-

nuages de points présents (2.5 %)

### création de Other/Unknown + le calculer 
- if / agrégation / for

### percentage data check 
###### - recalculer les pourcentage avec correction pour les NAN 
- faire liste, str et count ? 


### histogramme par pays - différente couleur par types
- groupby ?

In [32]:
ligne1 = df.iloc[1,:].values # prend les valeurs de la première ligne
total = 0 
[ligne1[i] for i in range(1,len(ligne1))]
 
print(np.sum([ligne1[i] for i in range(1,len(ligne1))] ))

nan

In [4]:
## faire une copie
df_count = df.iloc[:,:colonnes.index('Medical Neglect Only Percent')]
df_count.head()

,State,Medical Neglect Only,Neglect Only,Other Only,Physical Abuse Only,Psychological Maltreatment Only,Sexual Abuse Only,Sex Trafficking Only,Unknown Only,Multiple Maltreatment Types,Total Victims
0,Alabama,49.0,3380,NaN,5114,16.0,1828.0,3.0,NaN,1287,11677
1,Alaska,37.0,1445,NaN,111,327.0,183.0,1.0,NaN,955,3059
2,Arizona,NaN,11332,NaN,682,1.0,389.0,NaN,NaN,443,12847
3,Arkansas,1279.0,3421,1.0,1286,25.0,1415.0,NaN,NaN,995,8422
4,California,NaN,50799,117.0,2161,2115.0,2264.0,NaN,NaN,6659,64115

In [94]:
'''df_percent = df.iloc[:,colonnes.index('Medical Neglect Only Percent'):]
df_percent.head()'''

"df_percent = df.iloc[:,colonnes.index('Medical Neglect Only Percent'):]\ndf_percent.head()"

In [8]:
df_count.fillna(0)
#iloc[:,[colonnes.index('Other Only'),colonnes.index('Unknown Only')]].fillna(0)

#df_count['Unoroth'] =sum()
df_count
#[df.iloc[:,colonnes.index('Other Only')],df.iloc[:,colonnes.index('Unknown Only')]]

,State,Medical Neglect Only,Neglect Only,Other Only,Physical Abuse Only,Psychological Maltreatment Only,Sexual Abuse Only,Sex Trafficking Only,Unknown Only,Multiple Maltreatment Types,Total Victims
0,Alabama,49.0,3380,NaN,5114,16.0,1828.0,3.0,NaN,1287,11677
1,Alaska,37.0,1445,NaN,111,327.0,183.0,1.0,NaN,955,3059
2,Arizona,NaN,11332,NaN,682,1.0,389.0,NaN,NaN,443,12847
3,Arkansas,1279.0,3421,1.0,1286,25.0,1415.0,NaN,NaN,995,8422
4,California,NaN,50799,117.0,2161,2115.0,2264.0,NaN,NaN,6659,64115
5,Colorado,80.0,9517,NaN,854,126.0,990.0,NaN,9.0,670,12246
6,Connecticut,87.0,4709,NaN,172,599.0,181.0,NaN,NaN,2294,8042
7,Delaware,NaN,313,120.0,161,404.0,121.0,NaN,NaN,129,1248
8,District of Columbia,NaN,1492,NaN,175,NaN,45.0,14.0,NaN,131,1857
9,Florida,616.0,12893,8201.0,1742,156.0,2354.0,NaN,NaN,6953,32915
10,Georgia,148.0,5992,NaN,840,1447.0,693.0,27.0,NaN,955,10102
11,Hawaii,NaN,47,918.0,31,2.0,23.0,13.0,NaN,308,1342
12,Idaho,7.0,1349,3.0,306,NaN,100.0,NaN,NaN,104,1869
13,Illinois,441.0,22234,22.0,3856,29.0,3798.0,NaN,NaN,2951,33331
14,Indiana,NaN,19006,NaN,856,NaN,2060.0,4.0,NaN,1103,23029
15,Iowa,44.0,6105,1754.0,845,43.0,566.0,NaN,NaN,2291,11648
16,Kansas,58.0,1162,1.0,600,343.0,519.0,7.0,NaN,255,2945
17,Kentucky,127.0,17670,NaN,381,14.0,376.0,NaN,NaN,1562,20130
18,Louisiana,NaN,6954,NaN,690,11.0,339.0,1.0,NaN,446,8441
19,Maine,NaN,1839,NaN,460,679.0,217.0,NaN,NaN,1218,4413
20,Maryland,NaN,4221,NaN,1182,7.0,1748.0,NaN,NaN,503,7661
21,Massachusetts,NaN,22067,NaN,838,NaN,443.0,187.0,NaN,1494,25029
22,Michigan,349.0,25823,NaN,2950,103.0,676.0,14.0,NaN,3128,33043
23,Minnesota,NaN,4127,NaN,691,50.0,1292.0,20.0,NaN,600,6780
24,Mississippi,191.0,5202,1.0,777,480.0,888.0,3.0,NaN,1835,9377
25,Missouri,23.0,1549,5.0,665,90.0,1199.0,6.0,NaN,1225,4762
26,Montana,3.0,3444,NaN,44,3.0,39.0,NaN,NaN,203,3736
27,Nebraska,NaN,2190,NaN,229,4.0,228.0,NaN,NaN,171,2822
28,Nevada,33.0,3680,NaN,540,3.0,215.0,NaN,NaN,528,4999
29,New Hampshire,18.0,948,NaN,47,9.0,84.0,NaN,NaN,111,1217
30,New Jersey,65.0,3545,1.0,485,32.0,703.0,1.0,NaN,300,5132
31,New Mexico,67.0,4747,NaN,420,721.0,111.0,NaN,NaN,1959,8025
32,New York,453.0,38395,1564.0,547,40.0,345.0,NaN,NaN,25925,67269
33,North Carolina,49.0,2455,108.0,1575,105.0,1195.0,NaN,44.0,70,5601
34,North Dakota,6.0,1106,NaN,62,256.0,45.0,NaN,NaN,322,1797
35,Ohio,252.0,8333,NaN,8123,776.0,3905.0,NaN,NaN,4081,25470
36,Oklahoma,88.0,7824,NaN,849,2310.0,396.0,2.0,NaN,3679,15148
37,Oregon,64.0,4426,4595.0,861,72.0,757.0,18.0,NaN,2750,13543
38,Pennsylvania,160.0,373,21.0,1961,48.0,2007.0,17.0,NaN,230,4817
39,Puerto Rico,76.0,1576,10.0,245,815.0,41.0,NaN,NaN,1975,4738
40,Rhode Island,25.0,1436,51.0,288,802.0,110.0,NaN,NaN,471,3183
41,South Carolina,153.0,7073,13.0,7403,29.0,593.0,NaN,3.0,3450,18717
42,South Dakota,NaN,1319,NaN,76,2.0,39.0,NaN,NaN,101,1537
43,Tennessee,42.0,1199,NaN,4671,172.0,2159.0,88.0,NaN,1528,9859
44,Texas,417.0,48404,3.0,4086,116.0,5753.0,5.0,NaN,5309,64093
45,Utah,25.0,1953,105.0,2944,2051.0,1506.0,1.0,NaN,1994,10579
46,Vermont,11.0,13,NaN,463,1.0,327.0,NaN,NaN,36,851
47,Virginia,69.0,3444,NaN,1303,39.0,698.0,NaN,NaN,606,6159
48,Washington,NaN,2831,NaN,569,NaN,337.0,7.0,NaN,478,4222
49,West Virginia,NaN,1173,NaN,902,NaN,NaN,NaN,NaN,4652,6727
50,Wisconsin,NaN,2802,NaN,546,10.0,845.0,NaN,NaN,373,4576
51,Wyoming,2.0,655,NaN,13,189.0,60.0,NaN,NaN,177,1096
52,National,5614.0,399992,17614.0,67678,15672.0,47205.0,439.0,56.0,101973,656243
53,Reporting States,36.0,52,21.0,52,46.0,51.0,21.0,3.0,52,52

In [98]:
a = df.iloc[:,[colonnes.index('Other Only'),colonnes.index('Unknown Only')]].fillna(0)
a
#a.to_numpy()
df_count['Unoroth'] = pd.DataFrame(np.mean(a,axis = 1))
df_count
# pd.concat([pd.DataFrame(a[:,0]),df.iloc[:,colonnes.index('Other Only')]], axis = 1)

,State,Medical Neglect Only,Neglect Only,Other Only,Physical Abuse Only,Psychological Maltreatment Only,Sexual Abuse Only,Sex Trafficking Only,Unknown Only,Multiple Maltreatment Types,Total Victims,Unoroth
0,Alabama,49.0,3380,NaN,5114,16.0,1828.0,3.0,NaN,1287,11677,0.0
1,Alaska,37.0,1445,NaN,111,327.0,183.0,1.0,NaN,955,3059,0.0
2,Arizona,NaN,11332,NaN,682,1.0,389.0,NaN,NaN,443,12847,0.0
3,Arkansas,1279.0,3421,1.0,1286,25.0,1415.0,NaN,NaN,995,8422,0.5
4,California,NaN,50799,117.0,2161,2115.0,2264.0,NaN,NaN,6659,64115,58.5
5,Colorado,80.0,9517,NaN,854,126.0,990.0,NaN,9.0,670,12246,4.5
6,Connecticut,87.0,4709,NaN,172,599.0,181.0,NaN,NaN,2294,8042,0.0
7,Delaware,NaN,313,120.0,161,404.0,121.0,NaN,NaN,129,1248,60.0
8,District of Columbia,NaN,1492,NaN,175,NaN,45.0,14.0,NaN,131,1857,0.0
9,Florida,616.0,12893,8201.0,1742,156.0,2354.0,NaN,NaN,6953,32915,4100.5
10,Georgia,148.0,5992,NaN,840,1447.0,693.0,27.0,NaN,955,10102,0.0
11,Hawaii,NaN,47,918.0,31,2.0,23.0,13.0,NaN,308,1342,459.0
12,Idaho,7.0,1349,3.0,306,NaN,100.0,NaN,NaN,104,1869,1.5
13,Illinois,441.0,22234,22.0,3856,29.0,3798.0,NaN,NaN,2951,33331,11.0
14,Indiana,NaN,19006,NaN,856,NaN,2060.0,4.0,NaN,1103,23029,0.0
15,Iowa,44.0,6105,1754.0,845,43.0,566.0,NaN,NaN,2291,11648,877.0
16,Kansas,58.0,1162,1.0,600,343.0,519.0,7.0,NaN,255,2945,0.5
17,Kentucky,127.0,17670,NaN,381,14.0,376.0,NaN,NaN,1562,20130,0.0
18,Louisiana,NaN,6954,NaN,690,11.0,339.0,1.0,NaN,446,8441,0.0
19,Maine,NaN,1839,NaN,460,679.0,217.0,NaN,NaN,1218,4413,0.0
20,Maryland,NaN,4221,NaN,1182,7.0,1748.0,NaN,NaN,503,7661,0.0
21,Massachusetts,NaN,22067,NaN,838,NaN,443.0,187.0,NaN,1494,25029,0.0
22,Michigan,349.0,25823,NaN,2950,103.0,676.0,14.0,NaN,3128,33043,0.0
23,Minnesota,NaN,4127,NaN,691,50.0,1292.0,20.0,NaN,600,6780,0.0
24,Mississippi,191.0,5202,1.0,777,480.0,888.0,3.0,NaN,1835,9377,0.5
25,Missouri,23.0,1549,5.0,665,90.0,1199.0,6.0,NaN,1225,4762,2.5
26,Montana,3.0,3444,NaN,44,3.0,39.0,NaN,NaN,203,3736,0.0
27,Nebraska,NaN,2190,NaN,229,4.0,228.0,NaN,NaN,171,2822,0.0
28,Nevada,33.0,3680,NaN,540,3.0,215.0,NaN,NaN,528,4999,0.0
29,New Hampshire,18.0,948,NaN,47,9.0,84.0,NaN,NaN,111,1217,0.0
30,New Jersey,65.0,3545,1.0,485,32.0,703.0,1.0,NaN,300,5132,0.5
31,New Mexico,67.0,4747,NaN,420,721.0,111.0,NaN,NaN,1959,8025,0.0
32,New York,453.0,38395,1564.0,547,40.0,345.0,NaN,NaN,25925,67269,782.0
33,North Carolina,49.0,2455,108.0,1575,105.0,1195.0,NaN,44.0,70,5601,76.0
34,North Dakota,6.0,1106,NaN,62,256.0,45.0,NaN,NaN,322,1797,0.0
35,Ohio,252.0,8333,NaN,8123,776.0,3905.0,NaN,NaN,4081,25470,0.0
36,Oklahoma,88.0,7824,NaN,849,2310.0,396.0,2.0,NaN,3679,15148,0.0
37,Oregon,64.0,4426,4595.0,861,72.0,757.0,18.0,NaN,2750,13543,2297.5
38,Pennsylvania,160.0,373,21.0,1961,48.0,2007.0,17.0,NaN,230,4817,10.5
39,Puerto Rico,76.0,1576,10.0,245,815.0,41.0,NaN,NaN,1975,4738,5.0
40,Rhode Island,25.0,1436,51.0,288,802.0,110.0,NaN,NaN,471,3183,25.5
41,South Carolina,153.0,7073,13.0,7403,29.0,593.0,NaN,3.0,3450,18717,8.0
42,South Dakota,NaN,1319,NaN,76,2.0,39.0,NaN,NaN,101,1537,0.0
43,Tennessee,42.0,1199,NaN,4671,172.0,2159.0,88.0,NaN,1528,9859,0.0
44,Texas,417.0,48404,3.0,4086,116.0,5753.0,5.0,NaN,5309,64093,1.5
45,Utah,25.0,1953,105.0,2944,2051.0,1506.0,1.0,NaN,1994,10579,52.5
46,Vermont,11.0,13,NaN,463,1.0,327.0,NaN,NaN,36,851,0.0
47,Virginia,69.0,3444,NaN,1303,39.0,698.0,NaN,NaN,606,6159,0.0
48,Washington,NaN,2831,NaN,569,NaN,337.0,7.0,NaN,478,4222,0.0
49,West Virginia,NaN,1173,NaN,902,NaN,NaN,NaN,NaN,4652,6727,0.0
50,Wisconsin,NaN,2802,NaN,546,10.0,845.0,NaN,NaN,373,4576,0.0
51,Wyoming,2.0,655,NaN,13,189.0,60.0,NaN,NaN,177,1096,0.0
52,National,5614.0,399992,17614.0,67678,15672.0,47205.0,439.0,56.0,101973,656243,8835.0
53,Reporting States,36.0,52,21.0,52,46.0,51.0,21.0,3.0,52,52,12.0

In [52]:
row = 0
while row < len(colonnes):

IndentationError: expected an indented block (1065923861.py, line 2)